-- =========================================================
-- CREATE SUPERADMIN USER FOR MIZAN PLATFORM
-- =========================================================
--
-- User Credentials:
-- Email: anna@mizan.com
-- Password: MizanAdmin2024!
--
-- INSTRUCTIONS:
-- 1. First run create-superadmin.js to generate the password hash
-- 2. Replace [BCRYPT_HASH_HERE] below with the generated hash
-- 3. Execute this SQL in your Railway PostgreSQL database console
-- =========================================================

-- Step 1: Create superadmin tenant if it doesn't exist
INSERT INTO tenants (
  id,
  name,
  plan,
  status,
  created_at,
  updated_at
)
VALUES (
  '3fb789ff-63de-4e94-aee9-3c8bae9806e8',
  'Mizan Superadmin',
  'enterprise',
  'active',
  NOW(),
  NOW()
)
ON CONFLICT (id) DO NOTHING;

-- Step 2: Create the superadmin user
-- NOTE: Replace [BCRYPT_HASH_HERE] with the hash generated by create-superadmin.js
INSERT INTO users (
  tenant_id,
  email,
  password_hash,
  name,
  role,
  is_active,
  created_at,
  updated_at
)
VALUES (
  '3fb789ff-63de-4e94-aee9-3c8bae9806e8',
  'anna@mizan.com',
  '[BCRYPT_HASH_HERE]',  -- Replace this with the bcrypt hash from create-superadmin.js
  'Anna Dahrouj',
  'superadmin',
  true,
  NOW(),
  NOW()
)
ON CONFLICT (email) DO UPDATE SET
  role = 'superadmin',
  is_active = true,
  password_hash = EXCLUDED.password_hash,
  updated_at = NOW();

-- Verify the user was created
SELECT
  id,
  tenant_id,
  email,
  name,
  role,
  is_active,
  created_at
FROM users
WHERE email = 'anna@mizan.com';
